# Generated by Django 5.1.6 on 2025-02-17 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimage',
            name='caption',
        ),
        migrations.AddField(
            model_name='eventimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
